let AuraCapability = ReFactoryCapabilities.AURA

let altar = (id, input, output, aura, duration) => {
    ServerEvents.recipes(event => {
        event.recipes.gtceu.aura_altar(id)
            .itemInputs(input)
            .itemOutputs(output)
            .input(AuraCapability, aura)
            .duration(duration)
            .EUt(GTValues.VA[GTValues.MV])    
    })
}

let altarCatalyst = (id, input, output, aura, duration, catalyst) => {
    ServerEvents.recipes(event => {
        event.recipes.gtceu.aura_altar(id)
            .notConsumable(catalyst)
            .itemInputs(input)
            .itemOutputs(output)
            .input(AuraCapability, aura)
            .duration(duration)
            .EUt(GTValues.VA[GTValues.MV])
    })
}

altarCatalyst('amethyst', 'minecraft:amethyst_block', 'minecraft:amethyst_shard', 25000, 200, 'naturesaura:crushing_catalyst')
altarCatalyst('arrow', 'minecraft:arrow', 'minecraft:spectral_arrow', 10000, 50, 'naturesaura:conversion_catalyst')
altarCatalyst('blaze', 'minecraft:blaze_rod', '4x minecraft:blaze_powder', 5000, 60, 'naturesaura:crushing_catalyst')
altarCatalyst('bone', 'minecraft:bone', '6x minecraft:bone_meal', 3000, 40, 'naturesaura:crushing_catalyst')
altarCatalyst('chorus', 'minecraft:popped_chorus_fruit', 'minecraft:chorus_flower', 15000, 80, 'naturesaura:conversion_catalyst')
altarCatalyst('coal', 'minecraft:charcoal', 'minecraft:coal', 30000, 250, 'naturesaura:conversion_catalyst')
altarCatalyst('crimson_fungus', 'minecraft:red_mushroom', 'minecraft:crimson_fungus', 30000, 250, 'naturesaura:conversion_catalyst')
altarCatalyst('egg', 'minecraft:apple', 'minecraft:egg', 5000, 50, 'naturesaura:conversion_catalyst')
altarCatalyst('ender_pearl', 'minecraft:amethyst_shard', 'minecraft:ender_pearl', 90000, 300, 'naturesaura:conversion_catalyst')
altarCatalyst('fermented', 'minecraft:spider_eye', 'minecraft:fermented_spider_eye', 10000, 50, 'naturesaura:conversion_catalyst')
altarCatalyst('ghast_tear', 'minecraft:soul_soil', 'minecraft:ghast_tear', 90000, 300, 'naturesaura:conversion_catalyst')
altarCatalyst('gilded_blackstone', 'minecraft:blackstone', 'minecraft:gilded_blackstone', 50000, 300, 'naturesaura:conversion_catalyst')
altarCatalyst('glowstone', 'minecraft:glowstone', '4x minecraft:glowstone_dust', 3000, 40, 'naturesaura:crushing_catalyst')
altarCatalyst('gold_powder', 'naturesaura:gold_leaf', '4x naturesaura:gold_powder', 2000, 20, 'naturesaura:crushing_catalyst')
altar('infused_iron', 'minecraft:iron_ingot', 'naturesaura:infused_iron', 15000, 80)
altar('infused_iron_block', 'minecraft:iron_block', 'naturesaura:infused_iron_block', 135000, 700)
altar('infused_stone', 'minecraft:stone', 'naturesaura:infused_stone', 7500, 40)
altarCatalyst('lead', 'minecraft:string', 'minecraft:lead', 10000, 50, 'naturesaura:conversion_catalyst')
altarCatalyst('leather', 'minecraft:rotten_flesh', 'minecraft:leather', 10000, 50, 'naturesaura:conversion_catalyst')
altarCatalyst('milk', 'minecraft:water_bucket', 'minecraft:milk_bucket', 80000, 200, 'naturesaura:conversion_catalyst')
altarCatalyst('mud', 'minecraft:packed_mud', 'minecraft:mud', 2000, 20, 'naturesaura:crushing_catalyst')
altarCatalyst('nether_wart', 'minecraft:crimson_fungus', 'minecraft:nether_wart', 30000, 250, 'naturesaura:conversion_catalyst')
altarCatalyst('nether_wart_crushing', 'minecraft:nether_wart_block', 'minecraft:nether_wart', 25000, 200, 'naturesaura:crushing_catalyst')
altarCatalyst('potato', 'minecraft:poisonous_potato', 'minecraft:potato', 10000, 50, 'naturesaura:conversion_catalyst')
altarCatalyst('prismarine', 'minecraft:quartz', 'minecraft:prismarine_shard', 55000, 200, 'naturesaura:conversion_catalyst')
altarCatalyst('prismarine_crystal', 'minecraft:prismarine_shard', 'minecraft:prismarine_crystals', 55000, 200, 'naturesaura:conversion_catalyst')
altarCatalyst('rabbit_foot', 'minecraft:rabbit_stew', 'minecraft:rabbit_foot', 15000, 80, 'naturesaura:conversion_catalyst')
altarCatalyst('sand', 'minecraft:cobblestone', 'minecraft:sand', 3000, 40, 'naturesaura:crushing_catalyst')
altarCatalyst('soul_sand', 'minecraft:sand', 'minecraft:soul_sand', 5000, 100, 'naturesaura:conversion_catalyst')
altarCatalyst('soul_sand_crushing', 'minecraft:soul_soil', 'minecraft:soul_sand', 6000, 40, 'naturesaura:crushing_catalyst')
altarCatalyst('sugar', 'minecraft:sugar_cane', '3x minecraft:sugar', 3000, 40, 'naturesaura:crushing_catalyst')
altar('tainted_gold', 'minecraft:gold_ingot', 'naturesaura:tainted_gold', 3000, 300)
altar('tainted_gold_block', 'minecraft:gold_block', 'naturesaura:tainted_gold_block', 27000, 2625)
altarCatalyst('warped_fungus', 'minecraft:brown_mushroom', 'minecraft:warped_fungus', 30000, 250, 'naturesaura:conversion_catalyst')