StartupEvents.registry('block', event => {
    event.create('artificial_cloud_block')
        .displayName('Artificial Cloud Block')
        .soundType('wool')
        .tagBlock('aether:aether_portal_blocks')
        .requiresTool(true)
        .tagBlock('minecraft:mineable/pickaxe')

    event.create('mana_inert_casing')
        .displayName('Mana-Inert Casing')
        .hardness(10)
        .resistance(1)
        .lightLevel(0)
        .soundType('stone')
        .requiresTool(true)
        .tagBlock('mineable/pickaxe')
        .textureAll('kubejs:block/casings/mana_inert_casing')

    event.create('livingrock_casing')
        .displayName('Livingrock Casing')
        .hardness(10)
        .resistance(1)
        .lightLevel(0)
        .soundType('stone')
        .requiresTool(true)
        .tagBlock('mineable/pickaxe')
        .textureAll('kubejs:block/casings/livingrock_casing')

    event.create('nuclear_cladding')
        .displayName('Nuclear Cladding')
        .hardness(10)
        .resistance(1)
        .lightLevel(0)
        .soundType('stone')
        .requiresTool(true)
        .tagBlock('mineable/pickaxe')
        .textureAll('kubejs:block/casings/nuclear_cladding')

    event.create('control_rod_casing')
        .displayName('Control Rod Casing')
        .hardness(10)
        .resistance(1)
        .lightLevel(0)
        .soundType('stone')
        .requiresTool(true)
        .tagBlock('mineable/pickaxe')
        .textureAll('kubejs:block/casings/control_rod_casing')
})