GTCEuStartupEvents.registry('gtceu:machine', event => {

    event.create('essence_materializer', 'multiblock')
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType('essence_materializer')
        .appearanceBlock(() => GTBlocks.CASING_PTFE_INERT.get())
        .recipeModifiers([GTRecipeModifiers.ELECTRIC_OVERCLOCK.apply(OverclockingLogic.NON_PERFECT_OVERCLOCK)])
        .pattern(definition => FactoryBlockPattern.start()
            .aisle("aaa", "aaa", "aca", "aca", "aca", "aaa", "dad")
            .aisle("aaa", "aea", "cfc", "cfc", "cfc", "aea", "aga")
            .aisle("aaa", "aba", "aca", "aca", "aca", "aaa", "dad")

            .where("b", Predicates.controller(Predicates.blocks(definition.get())))
            .where("c", Predicates.blocks("gtceu:laminated_glass"))
            .where("d", Predicates.air())
            .where("e", Predicates.blocks("gtceu:rtm_alloy_coil_block"))
            .where("f", Predicates.blocks("gtceu:titanium_pipe_casing"))
            .where("g", Predicates.abilities(PartAbility.MUFFLER))
            .where("a", Predicates.blocks("gtceu:inert_machine_casing")
                .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS).setMaxGlobalLimited(1).setPreviewCount(1))
                .or(Predicates.abilities(PartAbility.EXPORT_FLUIDS).setMaxGlobalLimited(1).setPreviewCount(1))
                .or(Predicates.abilities(PartAbility.IMPORT_ITEMS).setMaxGlobalLimited(1).setPreviewCount(1))
                .or(Predicates.abilities(PartAbility.EXPORT_ITEMS).setMaxGlobalLimited(1).setPreviewCount(1))
                .or(Predicates.abilities(PartAbility.INPUT_ENERGY).setExactLimit(1).setPreviewCount(1))
                .or(Predicates.abilities(PartAbility.MAINTENANCE).setExactLimit(1).setPreviewCount(1))
            )
            .build())
        .model(GTMachineModels.createWorkableCasingMachineModel('gtceu:block/casings/solid/machine_casing_inert_ptfe', 'gtceu:block/multiblock/large_chemical_reactor'))
})