GTCEuStartupEvents.registry('gtceu:machine', event => {

    event.create('essence_ore_processor', 'multiblock')
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType('essence_ore_processor')
        .appearanceBlock(() => GTBlocks.FIREBOX_TITANIUM.get())
        .recipeModifiers([GTRecipeModifiers.ELECTRIC_OVERCLOCK.apply(OverclockingLogic.NON_PERFECT_OVERCLOCK)])
        .pattern(definition => FactoryBlockPattern.start()
            .aisle("aba", "ccc", "eee", "eee", "eee", "fef", "fef", "fef", "fef", "fff")
            .aisle("bab", "cgc", "ece", "ece", "ece", "ece", "ece", "ece", "ece", "fhf")
            .aisle("aba", "cdc", "eee", "eee", "eee", "fef", "fef", "fef", "fef", "fff")

            .where("d", Predicates.controller(Predicates.blocks(definition.get())))
            .where("a", Predicates.blocks("gtceu:stable_machine_casing"))
            .where("b", Predicates.blocks("gtceu:titanium_gearbox"))
            .where("e", Predicates.blocks("gtceu:stainless_steel_frame"))
            .where("f", Predicates.air())
            .where("g", Predicates.blocks("gtceu:rtm_alloy_coil_block"))
            .where("h", Predicates.ability(PartAbility.MUFFLER))
            .where("c", Predicates.blocks("gtceu:titanium_firebox_casing")
                .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS).setMaxGlobalLimited(1).setPreviewCount(1))
                .or(Predicates.abilities(PartAbility.IMPORT_ITEMS).setMaxGlobalLimited(1).setPreviewCount(1))
                .or(Predicates.abilities(PartAbility.EXPORT_ITEMS).setMaxGlobalLimited(1).setPreviewCount(1))
                .or(Predicates.abilities(PartAbility.INPUT_ENERGY).setExactLimit(1).setPreviewCount(1))
                .or(Predicates.abilities(PartAbility.MAINTENANCE).setExactLimit(1).setPreviewCount(1))
            )
            .build())
        .model(GTMachineModels.createWorkableCasingMachineModel('gtceu:block/casings/firebox/machine_casing_firebox_titanium', 'gtceu:block/multiblock/large_miner'))
})