GTCEuStartupEvents.registry('gtceu:machine', event => {

    event.create('essence_harvester', 'multiblock')
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType('essence_harvester')
        .appearanceBlock(() => GTBlocks.CASING_PTFE_INERT.get())
        .recipeModifiers([GTRecipeModifiers.ELECTRIC_OVERCLOCK.apply(OverclockingLogic.NON_PERFECT_OVERCLOCK)])
        .pattern(definition => FactoryBlockPattern.start()
            .aisle("abbba", "bcdcb", "bcdcb", "abbba")
            .aisle("bbbbb", "ceeec", "caaac", "bfffb")
            .aisle("bbbbb", "deeed", "daaad", "bfgfb")
            .aisle("bbbbb", "ceeec", "caaac", "bfffb")
            .aisle("abbba", "bcdcb", "bcdcb", "abbba")

            .where("g", Predicates.controller(Predicates.blocks(definition.get())))
            .where("a", Predicates.air())
            .where("c", Predicates.blocks("gtceu:laminated_glass"))
            .where("d", Predicates.blocks("gtceu:rtm_alloy_coil_block"))
            .where("e", Predicates.blocks("minecraft:dirt"))
            .where("f", Predicates.blocks("gtceu:filter_casing"))
            .where("b", Predicates.blocks("gtceu:inert_machine_casing")
                .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS).setMaxGlobalLimited(1).setPreviewCount(1))
                .or(Predicates.abilities(PartAbility.IMPORT_ITEMS).setMaxGlobalLimited(1).setPreviewCount(1))
                .or(Predicates.abilities(PartAbility.EXPORT_ITEMS).setMaxGlobalLimited(1).setPreviewCount(1))
                .or(Predicates.abilities(PartAbility.INPUT_ENERGY).setExactLimit(1).setPreviewCount(1))
                .or(Predicates.abilities(PartAbility.MAINTENANCE).setExactLimit(1).setPreviewCount(1))
            )
            .build())
        .model(GTMachineModels.createWorkableCasingMachineModel('gtceu:block/casings/solid/machine_casing_inert_ptfe', 'gtceu:block/multiblock/cleanroom'))
})