GTCEuStartupEvents.registry('gtceu:machine', event => {

    event.create('essence_crop_crossbreeder', 'multiblock')
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType('essence_crop_crossbreeder')
        .appearanceBlock(() => GTBlocks.CASING_PTFE_INERT.get())
        .recipeModifiers([GTRecipeModifiers.ELECTRIC_OVERCLOCK.apply(OverclockingLogic.NON_PERFECT_OVERCLOCK)])
        .pattern(definition => FactoryBlockPattern.start()
            .aisle("abbba", "bbbbb", "dbbbd", "daaad")
            .aisle("dbbbd", "efffe", "gdddg", "dghgd")
            .aisle("bbbbb", "biiib", "bbbbb", "daaad")
            .aisle("dbbbd", "efffe", "gdddg", "dghgd")
            .aisle("bbbbb", "biiib", "bbbbb", "daaad")
            .aisle("dbbbd", "efffe", "gdddg", "dghgd")
            .aisle("bbbbb", "biiib", "bbbbb", "daaad")
            .aisle("dbbbd", "efffe", "gdddg", "dghgd")
            .aisle("abbba", "bbcbb", "dbbbd", "daaad")

            .where("c", Predicates.controller(Predicates.blocks(definition.get())))
            .where("a", Predicates.blocks("gtceu:stainless_steel_frame"))
            .where("d", Predicates.air())
            .where("e", Predicates.blocks("gtceu:stainless_steel_gearbox"))
            .where("f", Predicates.blocks("minecraft:dirt"))
            .where("g", Predicates.blocks("gtceu:laminated_glass"))
            .where("h", Predicates.ability(PartAbility.MUFFLER))
            .where("i", Predicates.blocks("gtceu:titanium_pipe_casing"))
            .where("b", Predicates.blocks("gtceu:inert_machine_casing")
                .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS).setMaxGlobalLimited(1).setPreviewCount(1))
                .or(Predicates.abilities(PartAbility.IMPORT_ITEMS).setMaxGlobalLimited(4).setPreviewCount(4))
                .or(Predicates.abilities(PartAbility.EXPORT_ITEMS).setMaxGlobalLimited(2).setPreviewCount(1))
                .or(Predicates.abilities(PartAbility.INPUT_ENERGY).setExactLimit(1).setPreviewCount(1))
                .or(Predicates.abilities(PartAbility.MAINTENANCE).setExactLimit(1).setPreviewCount(1))
            )
            .build())
        .model(GTMachineModels.createSidedWorkableCasingMachineModel('gtceu:block/casings/solid/machine_casing_inert_ptfe', 'gtceu:block/multiblock/large_chemical_reactor'))
})