GTCEuStartupEvents.registry('gtceu:machine', event => {
    event.create('nuclear_reactor', 'multiblock')
        .rotationState(RotationState.NON_Y_AXIS)
        .recipeType('nuclear_reactor')
        .appearanceBlock(() => Block.getBlock('kubejs:nuclear_cladding'))
        .recipeModifiers([GTRecipeModifiers.ELECTRIC_OVERCLOCK.apply(OverclockingLogic.NON_PERFECT_OVERCLOCK)])
        .pattern(definition => FactoryBlockPattern.start()
            .aisle('BBBBBBB', 'BAAAAAB', 'BAAAAAB', 'BAAAAAB', 'BAAAAAB', 'BAAAAAB', 'BBBBBBB')
            .aisle('BAAAAAB', 'ADCDCDA', 'ADCDCDA', 'ADCDCDA', 'ADCDCDA', 'ADCDCDA', 'BAAAAAB')
            .aisle('BAAAAAB', 'ACDCDCA', 'ACDCDCA', 'ACDCDCA', 'ACDCDCA', 'ACDCDCA', 'BAAAAAB')
            .aisle('BAAAAAB', 'ADCDCDA', 'ADCDCDA', 'ADCDCDA', 'ADCDCDA', 'ADCDCDA', 'BAAAAAB')
            .aisle('BAAAAAB', 'ACDCDCA', 'ACDCDCA', 'ACDCDCA', 'ACDCDCA', 'ACDCDCA', 'BAAAAAB')
            .aisle('BAAAAAB', 'ADCDCDA', 'ADCDCDA', 'ADCDCDA', 'ADCDCDA', 'ADCDCDA', 'BAAAAAB')
            .aisle('BBBBBBB', 'BAAOAAB', 'BAAAAAB', 'BAAAAAB', 'BAAAAAB', 'BAAAAAB', 'BBBBBBB')
            .where('O', Predicates.controller(Predicates.blocks(definition.get())))
            .where('A', Predicates.blocks('kubejs:nuclear_cladding')
                .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS).setMaxGlobalLimited(2).setPreviewCount(2))
                .or(Predicates.abilities(PartAbility.EXPORT_FLUIDS).setMaxGlobalLimited(25).setPreviewCount(25))
                .or(Predicates.abilities(PartAbility.IMPORT_ITEMS).setMaxGlobalLimited(1).setPreviewCount(1))
                .or(Predicates.abilities(PartAbility.EXPORT_ITEMS).setMaxGlobalLimited(1).setPreviewCount(1))
                .or(Predicates.abilities(PartAbility.MAINTENANCE).setExactLimit(1).setPreviewCount(1))
            )
            .where('B', Predicates.blocks('kubejs:nuclear_cladding'))
            .where('C', Predicates.blocks('kubejs:control_rod_casing'))
            .where('D', Predicates.blocks(GTBlocks.CASING_STEEL_PIPE.get()))
            .build()
        )
        .workableCasingModel('kubejs:block/casings/nuclear_cladding', 'gtceu:block/multiblock/implosion_compressor')
})