GTCEuStartupEvents.registry("gtceu:machine", event => {
    event.create('perfect_daisy', 'multiblock')
        .rotationState(RotationState.ALL)
        .recipeType('perfect_daisy')
        .appearanceBlock(() => GTBlocks.CASING_INVAR_HEATPROOF.get())
        .recipeModifiers([GTRecipeModifiers.PARALLEL_HATCH, GTRecipeModifiers.ELECTRIC_OVERCLOCK.apply(OverclockingLogic.PERFECT_OVERCLOCK)])
        .pattern(definition => FactoryBlockPattern.start()
            .aisle("#######", "###C###", "#######", "#######", "#######", "##EEE##")
            .aisle("###C###", "###C###", "#######", "#######", "###E###", "#EEEEE#")
            .aisle("###C###", "#######", "#######", "###C###", "##E#E##", "EE###EE")
            .aisle("#CCCCC#", "CC#O#CC", "###C###", "##CCC##", "#E#H#E#", "EE###EE")
            .aisle("###C###", "#######", "#######", "###C###", "##E#E##", "EE###EE")
            .aisle("###C###", "###C###", "#######", "#######", "###E###", "#EEEEE#")
            .aisle("#######", "###C###", "#######", "#######", "#######", "##EEE##")
            .where("O", Predicates.controller(Predicates.blocks(definition.get())))
            .where("#", Predicates.any())
            .where("C", Predicates.blocks(GTBlocks.CASING_INVAR_HEATPROOF.get())
                .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS).setMaxGlobalLimited(1))
                .or(Predicates.abilities(PartAbility.EXPORT_FLUIDS).setMaxGlobalLimited(1))
                .or(Predicates.abilities(PartAbility.IMPORT_ITEMS).setMaxGlobalLimited(1))
                .or(Predicates.abilities(PartAbility.EXPORT_ITEMS).setMaxGlobalLimited(1))
                .or(Predicates.abilities(PartAbility.INPUT_ENERGY).setExactLimit(1).setPreviewCount(1))
                .or(Predicates.abilities(PartAbility.MAINTENANCE).setExactLimit(1).setPreviewCount(1))
            )
            .where("E", Predicates.blocks("kubejs:livingrock_casing"))
            .where("G", Predicates.blocks("botania:mana_diamond_block"))
            .where("H", Predicates.blocks("botania:dragonstone_block"))
            .build()
        )
        .workableCasingModel("gtceu:block/casings/solid/machine_casing_heatproof", 'gtceu:block/multiblock/implosion_compressor')
})