GTCEuStartupEvents.registry('gtceu:machine', event => {
    event.create('terra_nexus', 'multiblock')
        //.tooltips(Component.translatable('tooltip.gtceu.multiblock.terra_nexus'))
        .rotationState(RotationState.ALL)
        .recipeType('terra_nexus')
        .appearanceBlock(() => GTBlocks.CASING_STAINLESS_CLEAN.get())
        .recipeModifiers([GTRecipeModifiers.PARALLEL_HATCH, GTRecipeModifiers.ELECTRIC_OVERCLOCK.apply(OverclockingLogic.NON_PERFECT_OVERCLOCK)])
        .pattern(definition => FactoryBlockPattern.start()
            .aisle('LLLEEELLL', ' LLEEELL ', '         ')
            .aisle('LLLMMMLLL', 'LLLMMMLLL', ' LLMMMLL ')
            .aisle('LLLMMMLLL', 'LLLMMMLLL', ' LLMMMLL ')
            .aisle('EMMLLLMME', 'EMMLLLMME', ' MMLLLMM ')
            .aisle('EMMLLLMME', 'EMMLLLMME', ' MMLLLMM ')
            .aisle('EMMLLLMME', 'EMMLLLMME', ' MMLLLMM ')
            .aisle('LLLMMMLLL', 'LLLMMMLLL', ' LLMMMLL ')
            .aisle('LLLMMMLLL', 'LLLMMMLLL', ' LLMMMLL ')
            .aisle('LLLEEELLL', ' LLEOELL ', '         ')
            .where('O', Predicates.controller(Predicates.blocks(definition.get())))
            .where(' ', Predicates.any())
            .where('E', Predicates.blocks('kubejs:mana_inert_casing')
                .or(Predicates.abilities(PartAbility.IMPORT_FLUIDS).setMaxGlobalLimited(4))
                .or(Predicates.abilities(PartAbility.EXPORT_FLUIDS).setMaxGlobalLimited(4))
                .or(Predicates.abilities(PartAbility.IMPORT_ITEMS).setMaxGlobalLimited(2))
                .or(Predicates.abilities(PartAbility.EXPORT_ITEMS).setMaxGlobalLimited(2))
                .or(Predicates.abilities(PartAbility.INPUT_ENERGY).setExactLimit(1).setPreviewCount(1))
                .or(Predicates.abilities(PartAbility.MAINTENANCE).setExactLimit(1).setPreviewCount(1))
            )
            .where('M', Predicates.blocks('kubejs:mana_inert_casing'))
            .where('L', Predicates.blocks('kubejs:livingrock_casing'))
            .build()
        )
        .workableCasingModel('kubejs:block/casings/mana_inert_casing', 'gtceu:block/multiblock/implosion_compressor')
})